package sn.stn.facturation.domain;

import static org.assertj.core.api.Assertions.assertThat;

public class FactureAsserts {

    /**
     * Asserts that the entity has all properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertFactureAllPropertiesEquals(Facture expected, Facture actual) {
        assertFactureAutoGeneratedPropertiesEquals(expected, actual);
        assertFactureAllUpdatablePropertiesEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all updatable properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertFactureAllUpdatablePropertiesEquals(Facture expected, Facture actual) {
        assertFactureUpdatableFieldsEquals(expected, actual);
        assertFactureUpdatableRelationshipsEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all the auto generated properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertFactureAutoGeneratedPropertiesEquals(Facture expected, Facture actual) {
        assertThat(actual)
            .as("Verify Facture auto generated properties")
            .satisfies(a -> assertThat(a.getId()).as("check id").isEqualTo(expected.getId()));
    }

    /**
     * Asserts that the entity has all the updatable fields set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertFactureUpdatableFieldsEquals(Facture expected, Facture actual) {
        assertThat(actual)
            .as("Verify Facture relevant properties")
            .satisfies(a -> assertThat(a.getNumero()).as("check numero").isEqualTo(expected.getNumero()))
            .satisfies(a -> assertThat(a.getDateEmission()).as("check dateEmission").isEqualTo(expected.getDateEmission()))
            .satisfies(a -> assertThat(a.getDatePaiement()).as("check datePaiement").isEqualTo(expected.getDatePaiement()))
            .satisfies(a -> assertThat(a.getVolumeM3()).as("check volumeM3").isEqualTo(expected.getVolumeM3()))
            .satisfies(a -> assertThat(a.getMontantBaseHt()).as("check montantBaseHt").isEqualTo(expected.getMontantBaseHt()))
            .satisfies(a ->
                assertThat(a.getMontantSupplementsHt()).as("check montantSupplementsHt").isEqualTo(expected.getMontantSupplementsHt())
            )
            .satisfies(a -> assertThat(a.getMontantHt()).as("check montantHt").isEqualTo(expected.getMontantHt()))
            .satisfies(a -> assertThat(a.getTauxTva()).as("check tauxTva").isEqualTo(expected.getTauxTva()))
            .satisfies(a -> assertThat(a.getMontantTva()).as("check montantTva").isEqualTo(expected.getMontantTva()))
            .satisfies(a -> assertThat(a.getMontantTtc()).as("check montantTtc").isEqualTo(expected.getMontantTtc()))
            .satisfies(a -> assertThat(a.getDevise()).as("check devise").isEqualTo(expected.getDevise()))
            .satisfies(a -> assertThat(a.getTauxChangeCfa()).as("check tauxChangeCfa").isEqualTo(expected.getTauxChangeCfa()))
            .satisfies(a -> assertThat(a.getStatut()).as("check statut").isEqualTo(expected.getStatut()))
            .satisfies(a -> assertThat(a.getNotes()).as("check notes").isEqualTo(expected.getNotes()))
            .satisfies(a -> assertThat(a.getCheminPdf()).as("check cheminPdf").isEqualTo(expected.getCheminPdf()))
            .satisfies(a -> assertThat(a.getCreeParLogin()).as("check creeParLogin").isEqualTo(expected.getCreeParLogin()));
    }

    /**
     * Asserts that the entity has all the updatable relationships set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertFactureUpdatableRelationshipsEquals(Facture expected, Facture actual) {
        assertThat(actual)
            .as("Verify Facture relationships")
            .satisfies(a -> assertThat(a.getNavire()).as("check navire").isEqualTo(expected.getNavire()))
            .satisfies(a -> assertThat(a.getClient()).as("check client").isEqualTo(expected.getClient()));
    }
}
