package sn.stn.facturation.domain;

import static org.assertj.core.api.Assertions.assertThat;

public class HistoriqueTarifAsserts {

    /**
     * Asserts that the entity has all properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertHistoriqueTarifAllPropertiesEquals(HistoriqueTarif expected, HistoriqueTarif actual) {
        assertHistoriqueTarifAutoGeneratedPropertiesEquals(expected, actual);
        assertHistoriqueTarifAllUpdatablePropertiesEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all updatable properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertHistoriqueTarifAllUpdatablePropertiesEquals(HistoriqueTarif expected, HistoriqueTarif actual) {
        assertHistoriqueTarifUpdatableFieldsEquals(expected, actual);
        assertHistoriqueTarifUpdatableRelationshipsEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all the auto generated properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertHistoriqueTarifAutoGeneratedPropertiesEquals(HistoriqueTarif expected, HistoriqueTarif actual) {
        assertThat(actual)
            .as("Verify HistoriqueTarif auto generated properties")
            .satisfies(a -> assertThat(a.getId()).as("check id").isEqualTo(expected.getId()));
    }

    /**
     * Asserts that the entity has all the updatable fields set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertHistoriqueTarifUpdatableFieldsEquals(HistoriqueTarif expected, HistoriqueTarif actual) {
        assertThat(actual)
            .as("Verify HistoriqueTarif relevant properties")
            .satisfies(a -> assertThat(a.getAncienneValeur()).as("check ancienneValeur").isEqualTo(expected.getAncienneValeur()))
            .satisfies(a -> assertThat(a.getNouvelleValeur()).as("check nouvelleValeur").isEqualTo(expected.getNouvelleValeur()))
            .satisfies(a -> assertThat(a.getDateModification()).as("check dateModification").isEqualTo(expected.getDateModification()))
            .satisfies(a -> assertThat(a.getCommentaire()).as("check commentaire").isEqualTo(expected.getCommentaire()))
            .satisfies(a -> assertThat(a.getModifieParLogin()).as("check modifieParLogin").isEqualTo(expected.getModifieParLogin()));
    }

    /**
     * Asserts that the entity has all the updatable relationships set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertHistoriqueTarifUpdatableRelationshipsEquals(HistoriqueTarif expected, HistoriqueTarif actual) {
        assertThat(actual)
            .as("Verify HistoriqueTarif relationships")
            .satisfies(a -> assertThat(a.getTarif()).as("check tarif").isEqualTo(expected.getTarif()));
    }
}
