package sn.stn.facturation.domain;

import static org.assertj.core.api.Assertions.assertThat;

public class LigneFactureSupplementAsserts {

    /**
     * Asserts that the entity has all properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertLigneFactureSupplementAllPropertiesEquals(LigneFactureSupplement expected, LigneFactureSupplement actual) {
        assertLigneFactureSupplementAutoGeneratedPropertiesEquals(expected, actual);
        assertLigneFactureSupplementAllUpdatablePropertiesEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all updatable properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertLigneFactureSupplementAllUpdatablePropertiesEquals(
        LigneFactureSupplement expected,
        LigneFactureSupplement actual
    ) {
        assertLigneFactureSupplementUpdatableFieldsEquals(expected, actual);
        assertLigneFactureSupplementUpdatableRelationshipsEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all the auto generated properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertLigneFactureSupplementAutoGeneratedPropertiesEquals(
        LigneFactureSupplement expected,
        LigneFactureSupplement actual
    ) {
        assertThat(actual)
            .as("Verify LigneFactureSupplement auto generated properties")
            .satisfies(a -> assertThat(a.getId()).as("check id").isEqualTo(expected.getId()));
    }

    /**
     * Asserts that the entity has all the updatable fields set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertLigneFactureSupplementUpdatableFieldsEquals(LigneFactureSupplement expected, LigneFactureSupplement actual) {
        assertThat(actual)
            .as("Verify LigneFactureSupplement relevant properties")
            .satisfies(a -> assertThat(a.getMontantCalcule()).as("check montantCalcule").isEqualTo(expected.getMontantCalcule()))
            .satisfies(a -> assertThat(a.getDescription()).as("check description").isEqualTo(expected.getDescription()));
    }

    /**
     * Asserts that the entity has all the updatable relationships set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertLigneFactureSupplementUpdatableRelationshipsEquals(
        LigneFactureSupplement expected,
        LigneFactureSupplement actual
    ) {
        assertThat(actual)
            .as("Verify LigneFactureSupplement relationships")
            .satisfies(a -> assertThat(a.getSupplement()).as("check supplement").isEqualTo(expected.getSupplement()))
            .satisfies(a -> assertThat(a.getFacture()).as("check facture").isEqualTo(expected.getFacture()));
    }
}
