package sn.stn.facturation.domain;

import static org.assertj.core.api.Assertions.assertThat;

public class MouvementAsserts {

    /**
     * Asserts that the entity has all properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertMouvementAllPropertiesEquals(Mouvement expected, Mouvement actual) {
        assertMouvementAutoGeneratedPropertiesEquals(expected, actual);
        assertMouvementAllUpdatablePropertiesEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all updatable properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertMouvementAllUpdatablePropertiesEquals(Mouvement expected, Mouvement actual) {
        assertMouvementUpdatableFieldsEquals(expected, actual);
        assertMouvementUpdatableRelationshipsEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all the auto generated properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertMouvementAutoGeneratedPropertiesEquals(Mouvement expected, Mouvement actual) {
        assertThat(actual)
            .as("Verify Mouvement auto generated properties")
            .satisfies(a -> assertThat(a.getId()).as("check id").isEqualTo(expected.getId()));
    }

    /**
     * Asserts that the entity has all the updatable fields set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertMouvementUpdatableFieldsEquals(Mouvement expected, Mouvement actual) {
        assertThat(actual)
            .as("Verify Mouvement relevant properties")
            .satisfies(a -> assertThat(a.getType()).as("check type").isEqualTo(expected.getType()))
            .satisfies(a -> assertThat(a.getPosteA()).as("check posteA").isEqualTo(expected.getPosteA()))
            .satisfies(a -> assertThat(a.getPosteB()).as("check posteB").isEqualTo(expected.getPosteB()))
            .satisfies(a -> assertThat(a.getDuree()).as("check duree").isEqualTo(expected.getDuree()))
            .satisfies(a -> assertThat(a.getMontantCalcule()).as("check montantCalcule").isEqualTo(expected.getMontantCalcule()))
            .satisfies(a -> assertThat(a.getLibelle()).as("check libelle").isEqualTo(expected.getLibelle()));
    }

    /**
     * Asserts that the entity has all the updatable relationships set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertMouvementUpdatableRelationshipsEquals(Mouvement expected, Mouvement actual) {
        assertThat(actual)
            .as("Verify Mouvement relationships")
            .satisfies(a -> assertThat(a.getRemorqueur()).as("check remorqueur").isEqualTo(expected.getRemorqueur()))
            .satisfies(a -> assertThat(a.getFacture()).as("check facture").isEqualTo(expected.getFacture()));
    }
}
