package sn.stn.facturation.domain;

import static org.assertj.core.api.Assertions.assertThat;

public class NavireAsserts {

    /**
     * Asserts that the entity has all properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertNavireAllPropertiesEquals(Navire expected, Navire actual) {
        assertNavireAutoGeneratedPropertiesEquals(expected, actual);
        assertNavireAllUpdatablePropertiesEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all updatable properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertNavireAllUpdatablePropertiesEquals(Navire expected, Navire actual) {
        assertNavireUpdatableFieldsEquals(expected, actual);
        assertNavireUpdatableRelationshipsEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all the auto generated properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertNavireAutoGeneratedPropertiesEquals(Navire expected, Navire actual) {
        assertThat(actual)
            .as("Verify Navire auto generated properties")
            .satisfies(a -> assertThat(a.getId()).as("check id").isEqualTo(expected.getId()));
    }

    /**
     * Asserts that the entity has all the updatable fields set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertNavireUpdatableFieldsEquals(Navire expected, Navire actual) {
        assertThat(actual)
            .as("Verify Navire relevant properties")
            .satisfies(a -> assertThat(a.getNom()).as("check nom").isEqualTo(expected.getNom()))
            .satisfies(a -> assertThat(a.getNumeroImo()).as("check numeroImo").isEqualTo(expected.getNumeroImo()))
            .satisfies(a -> assertThat(a.getJaugeBrute()).as("check jaugeBrute").isEqualTo(expected.getJaugeBrute()))
            .satisfies(a -> assertThat(a.getLongueur()).as("check longueur").isEqualTo(expected.getLongueur()))
            .satisfies(a -> assertThat(a.getLargeur()).as("check largeur").isEqualTo(expected.getLargeur()))
            .satisfies(a -> assertThat(a.getTirant()).as("check tirant").isEqualTo(expected.getTirant()))
            .satisfies(a -> assertThat(a.getPavillon()).as("check pavillon").isEqualTo(expected.getPavillon()))
            .satisfies(a -> assertThat(a.getActif()).as("check actif").isEqualTo(expected.getActif()));
    }

    /**
     * Asserts that the entity has all the updatable relationships set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertNavireUpdatableRelationshipsEquals(Navire expected, Navire actual) {
        assertThat(actual)
            .as("Verify Navire relationships")
            .satisfies(a -> assertThat(a.getClient()).as("check client").isEqualTo(expected.getClient()));
    }
}
