package sn.stn.facturation.domain;

import static org.assertj.core.api.Assertions.assertThat;

public class RemorqueurAsserts {

    /**
     * Asserts that the entity has all properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertRemorqueurAllPropertiesEquals(Remorqueur expected, Remorqueur actual) {
        assertRemorqueurAutoGeneratedPropertiesEquals(expected, actual);
        assertRemorqueurAllUpdatablePropertiesEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all updatable properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertRemorqueurAllUpdatablePropertiesEquals(Remorqueur expected, Remorqueur actual) {
        assertRemorqueurUpdatableFieldsEquals(expected, actual);
        assertRemorqueurUpdatableRelationshipsEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all the auto generated properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertRemorqueurAutoGeneratedPropertiesEquals(Remorqueur expected, Remorqueur actual) {
        assertThat(actual)
            .as("Verify Remorqueur auto generated properties")
            .satisfies(a -> assertThat(a.getId()).as("check id").isEqualTo(expected.getId()));
    }

    /**
     * Asserts that the entity has all the updatable fields set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertRemorqueurUpdatableFieldsEquals(Remorqueur expected, Remorqueur actual) {
        assertThat(actual)
            .as("Verify Remorqueur relevant properties")
            .satisfies(a -> assertThat(a.getCode()).as("check code").isEqualTo(expected.getCode()))
            .satisfies(a -> assertThat(a.getNom()).as("check nom").isEqualTo(expected.getNom()))
            .satisfies(a -> assertThat(a.getStatut()).as("check statut").isEqualTo(expected.getStatut()))
            .satisfies(a -> assertThat(a.getObservation()).as("check observation").isEqualTo(expected.getObservation()));
    }

    /**
     * Asserts that the entity has all the updatable relationships set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertRemorqueurUpdatableRelationshipsEquals(Remorqueur expected, Remorqueur actual) {
        // empty method
    }
}
