package sn.stn.facturation.domain;

import static org.assertj.core.api.Assertions.assertThat;

public class SupplementAsserts {

    /**
     * Asserts that the entity has all properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertSupplementAllPropertiesEquals(Supplement expected, Supplement actual) {
        assertSupplementAutoGeneratedPropertiesEquals(expected, actual);
        assertSupplementAllUpdatablePropertiesEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all updatable properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertSupplementAllUpdatablePropertiesEquals(Supplement expected, Supplement actual) {
        assertSupplementUpdatableFieldsEquals(expected, actual);
        assertSupplementUpdatableRelationshipsEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all the auto generated properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertSupplementAutoGeneratedPropertiesEquals(Supplement expected, Supplement actual) {
        assertThat(actual)
            .as("Verify Supplement auto generated properties")
            .satisfies(a -> assertThat(a.getId()).as("check id").isEqualTo(expected.getId()));
    }

    /**
     * Asserts that the entity has all the updatable fields set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertSupplementUpdatableFieldsEquals(Supplement expected, Supplement actual) {
        assertThat(actual)
            .as("Verify Supplement relevant properties")
            .satisfies(a -> assertThat(a.getCode()).as("check code").isEqualTo(expected.getCode()))
            .satisfies(a -> assertThat(a.getLibelle()).as("check libelle").isEqualTo(expected.getLibelle()))
            .satisfies(a -> assertThat(a.getType()).as("check type").isEqualTo(expected.getType()))
            .satisfies(a -> assertThat(a.getTauxPourcentage()).as("check tauxPourcentage").isEqualTo(expected.getTauxPourcentage()))
            .satisfies(a -> assertThat(a.getMontantFixe()).as("check montantFixe").isEqualTo(expected.getMontantFixe()))
            .satisfies(a -> assertThat(a.getActif()).as("check actif").isEqualTo(expected.getActif()));
    }

    /**
     * Asserts that the entity has all the updatable relationships set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertSupplementUpdatableRelationshipsEquals(Supplement expected, Supplement actual) {
        // empty method
    }
}
