package sn.stn.facturation.domain;

import static org.assertj.core.api.Assertions.assertThat;

public class TarifAsserts {

    /**
     * Asserts that the entity has all properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertTarifAllPropertiesEquals(Tarif expected, Tarif actual) {
        assertTarifAutoGeneratedPropertiesEquals(expected, actual);
        assertTarifAllUpdatablePropertiesEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all updatable properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertTarifAllUpdatablePropertiesEquals(Tarif expected, Tarif actual) {
        assertTarifUpdatableFieldsEquals(expected, actual);
        assertTarifUpdatableRelationshipsEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all the auto generated properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertTarifAutoGeneratedPropertiesEquals(Tarif expected, Tarif actual) {
        assertThat(actual)
            .as("Verify Tarif auto generated properties")
            .satisfies(a -> assertThat(a.getId()).as("check id").isEqualTo(expected.getId()));
    }

    /**
     * Asserts that the entity has all the updatable fields set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertTarifUpdatableFieldsEquals(Tarif expected, Tarif actual) {
        assertThat(actual)
            .as("Verify Tarif relevant properties")
            .satisfies(a -> assertThat(a.getTrancheMin()).as("check trancheMin").isEqualTo(expected.getTrancheMin()))
            .satisfies(a -> assertThat(a.getTrancheMax()).as("check trancheMax").isEqualTo(expected.getTrancheMax()))
            .satisfies(a -> assertThat(a.getPrixEuro()).as("check prixEuro").isEqualTo(expected.getPrixEuro()))
            .satisfies(a -> assertThat(a.getActif()).as("check actif").isEqualTo(expected.getActif()))
            .satisfies(a -> assertThat(a.getDateDebut()).as("check dateDebut").isEqualTo(expected.getDateDebut()))
            .satisfies(a -> assertThat(a.getDateFin()).as("check dateFin").isEqualTo(expected.getDateFin()))
            .satisfies(a -> assertThat(a.getDescription()).as("check description").isEqualTo(expected.getDescription()));
    }

    /**
     * Asserts that the entity has all the updatable relationships set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertTarifUpdatableRelationshipsEquals(Tarif expected, Tarif actual) {
        // empty method
    }
}
